// <auto-generated />
namespace FinalTest.Data.EntityFrame.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class dislikesamount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dislikesamount));
        
        string IMigrationMetadata.Id
        {
            get { return "201907031729397_dislikesamount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
